export class IssuesMemberModel{
  codeProject?:any;
  issuesId?:number;
  issuesNo?:any;
  projectId?:any;
  pm?:any;
  author?:any;
  assignee?:any;
  createdOn?:any;
  dueDate?:any;
  actualProcessingTime?:any;
  priority?:any;
  severity?:any;
  status?:any;
  problem?:any;
  description?:any;
  reason?:any;
  solution?:any;
  lessonsLearn?:any
}
